name: Build and test
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 12
        include:
          - node: 10
            os: ubuntu-latest
          - node: 14
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install # also runs the `prepare` npm script, which runs `build`
      - run: npm test
