name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    name: 'Build and test: Node v${{ matrix.node }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2019
        node:
          - 16
        include:
          - node: 12
            os: ubuntu-latest
          - node: 14
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Update npm
        run: npm install -g npm@7
        # It looks like npm v8 doesn't work with the error:
        # "Cannot set properties of null (setting 'parent')"
      - run: npm install # also runs the `prepare` npm script, which runs `build`
      - run: npm test
  integration-tests:
    name: 'Integration tests: TDLib ${{ matrix.tdlib.ver }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        tdlib:
          - { ver: v1.8.6, ref: 15db91b536d796778b628fef3d60923cef351512 }
          - { ver: v1.8.0, ref: v1.8.0 }
          - { ver: v1.7.0, ref: v1.7.0 }
          - { ver: v1.6.0, ref: v1.6.0 }
          - { ver: v1.5.0, ref: v1.6.0 }
        node:
          - 16
    env:
      LIBTDJSON_PATH: tdlib/build/libtdjson.so
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Update npm
        run: npm install -g npm@7
      - run: npm install
      - name: TDLib build cache
        id: tdlib-cache
        uses: actions/cache@v2
        with:
          path: tdlib/build/*.so*
          key: ${{ matrix.os }}-tdlib-${{ matrix.tdlib.ref }}
      - name: Build TDLib
        if: steps.tdlib-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y -q gperf
          git clone https://github.com/tdlib/td.git tdlib
          cd tdlib
          git checkout ${{ matrix.tdlib.ref }}
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --target tdjson -- -j 2
      - run: npm run integration-tests
