name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    name: 'Test / Node v${{ matrix.node }} / ${{ matrix.os }})'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 20
        include:
          # tdl should still work with node v12 and v14, however the dev
          # deps in this repository don't support those versions
          - node: 16
            os: ubuntu-latest
          - node: 18
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Update npm
        run: npm install -g npm@9
      - run: npm install # also runs the `prepare` npm script, which runs `build`
      - run: npm test
      - name: Run integration tests
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $tds = @(
            "td-1.8.26",
            "td-1.8.25",
            "td-1.8.19",
            "td-1.8.14",
            "td-1.8.5",
            "td-1.8.0",
            "td-1.7.0",
            "td-1.5.0"
          )
          foreach ($td in $tds) {
            mkdir $td
            npm pack prebuilt-tdlib@$td --pack-destination=$td
            Get-ChildItem -Path $td -Filter *.tgz | ForEach-Object {
              tar xzvf $_.FullName --directory=$td
            }
            rm $td/package/package.json
            $env:USE_PREBUILT="$td/package/index.js"
            npm run integration-tests
            if ($LastExitCode -ne 0) {
              exit $LastExitCode
            }
          }
