name: Build and test
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 12
    name: Node ${{ matrix.node }} on ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install # also runs the `prepare` npm script, which runs `build`
      - run: npm test
